Num1 = int(input("enter the first number:"))
Num2 = int(input("enter the second number:"))
print("Sum of two numbers:",Num1+Num2)
print("Substraction of two numbers:",Num1-Num2)
print("Multiply of two numbers:",Num1*Num2)
print("Division of two numbers:",Num1/Num2)
print("Modulus of two numbers:",Num1%Num2)
print("program end")